use_frameworks!

platform :ios, '10.0'

source 'https://cdn.cocoapods.org/'
source 'https://github.com/zoubenjun/ZBJPoplarRepo.git'

#install! 'cocoapods', :warn_for_multiple_pod_sources => false, :deterministic_uuids => false
install! 'cocoapods', :warn_for_multiple_pod_sources => true, :deterministic_uuids => false
#project 'Example/ZBJBaseProject.xcodeproj'

inhibit_all_warnings!

target 'ZBJBaseProject' do
  pod 'ZBJBasicKit', :path => '../', :inhibit_warnings => false
  pod 'ZBJHomeKit', :path => '../', :inhibit_warnings => false

  pod 'ZBJPoplar', '0.1.14'

  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'Masonry'
  pod 'MJExtension'
  pod 'YYModel'
  pod 'ReactiveObjC', '~> 3.0.0'

  target 'ZBJBaseProject_Tests' do
    inherit! :search_paths
  end
  
end
